# Generated by Django 5.0.4 on 2024-06-04 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='商品类别表',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名称', models.CharField(max_length=50, unique=True)),
                ('描述', models.TextField(blank=True)),
                ('图片', models.ImageField(blank=True, upload_to='category')),
            ],
            options={
                'verbose_name_plural': '商品类别表',
                'db_table': '商品类别表',
            },
        ),
        migrations.CreateModel(
            name='商品列表',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名称', models.CharField(max_length=150, unique=True)),
                ('描述', models.TextField(blank=True)),
                ('图片', models.ImageField(blank=True, upload_to='category')),
                ('价格', models.DecimalField(decimal_places=2, max_digits=10)),
                ('库存', models.IntegerField(default=0)),
                ('已上架', models.BooleanField(default=True)),
                ('创建时间', models.DateTimeField(auto_now_add=True)),
                ('修改时间', models.DateTimeField(auto_now_add=True)),
                ('所属类别', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.商品类别表')),
            ],
            options={
                'verbose_name_plural': '商品列表',
                'db_table': '商品列表',
                'ordering': ('-创建时间',),
            },
        ),
    ]
