# Generated by Django 5.0.4 on 2024-06-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='商品列表',
            name='作者',
            field=models.CharField(blank=True),
        ),
    ]
