# Generated by Django 5.0.4 on 2024-05-31 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_extend',
            old_name='name',
            new_name='姓名',
        ),
        migrations.RenameField(
            model_name='user_extend',
            old_name='phone',
            new_name='手机号',
        ),
        migrations.RenameField(
            model_name='user_extend',
            old_name='nickname',
            new_name='昵称',
        ),
    ]
