# Generated by Django 5.0.4 on 2024-06-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_name_user_extend_姓名_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_extend',
            name='姓名',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user_extend',
            name='手机号',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='user_extend',
            name='昵称',
            field=models.CharField(max_length=15),
        ),
    ]
